/*
 * This source file was generated by the Gradle 'init' task
 */
package com.discc;

import org.junit.jupiter.api.Test;

class Pojo2AvscGeneratorTest {
    @Test void someLibraryMethodReturnsTrue() {
        Pojo2AvscGenerator classUnderTest = new Pojo2AvscGenerator();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
